import type { ImageSourcePropType } from 'react-native';

export type CircleCategory = {
  id: string;
  slug: string;
  label: string;
  image: ImageSourcePropType;
};

/** Screenshot order first, then the rest of the shipped circle art. */
const ORDER: { slug: string; label: string; file: string }[] = [
  { slug: 'biryani', label: 'Biryani', file: 'biryani.webp' },
  { slug: 'pizza', label: 'Pizza', file: 'pizza.webp' },
  { slug: 'burger', label: 'Burgers', file: 'burger.webp' },
  { slug: 'rolls', label: 'Rolls', file: 'rolls_wraps.webp' },
  { slug: 'noodles', label: 'Noodles', file: 'noodles.webp' },
  { slug: 'momos', label: 'Momos', file: 'momos.webp' },
  { slug: 'chinese', label: 'Chinese', file: 'chinese.webp' },
  { slug: 'south_indian', label: 'South Indian', file: 'south_indian.webp' },
  { slug: 'north_indian', label: 'North Indian', file: 'north_indian.webp' },
  { slug: 'dosa', label: 'Dosa', file: 'dosa.webp' },
  { slug: 'idli', label: 'Idli', file: 'idli.webp' },
  { slug: 'thali', label: 'Thali', file: 'thali.webp' },
  { slug: 'paratha', label: 'Paratha', file: 'paratha.webp' },
  { slug: 'pav_bhaji', label: 'Pav Bhaji', file: 'pav_bhaji.webp' },
  { slug: 'vada_pav', label: 'Vada Pav', file: 'vada_pav.webp' },
  { slug: 'chole_bhature', label: 'Chole Bhature', file: 'chole_bhature.webp' },
  { slug: 'poori_bhaji', label: 'Poori Bhaji', file: 'poori_bhaji.webp' },
  { slug: 'rajma_chawal', label: 'Rajma Chawal', file: 'rajma_chawal.webp' },
  { slug: 'chaat', label: 'Chaat', file: 'chaat.webp' },
  { slug: 'samosa', label: 'Samosa', file: 'samosa.webp' },
  { slug: 'kachori', label: 'Kachori', file: 'kachori.webp' },
  { slug: 'street_food', label: 'Street Food', file: 'street_food.webp' },
  { slug: 'snacks', label: 'Snacks', file: 'snacks.webp' },
  { slug: 'sandwich', label: 'Sandwich', file: 'sandwich.webp' },
  { slug: 'shawarma', label: 'Shawarma', file: 'shawarma.webp' },
  { slug: 'kebabs', label: 'Kebabs', file: 'kebabs.webp' },
  { slug: 'tandoori', label: 'Tandoori', file: 'tandoori.webp' },
  { slug: 'bbq', label: 'BBQ', file: 'bbq.webp' },
  { slug: 'chicken', label: 'Chicken', file: 'chicken.webp' },
  { slug: 'mutton', label: 'Mutton', file: 'mutton.webp' },
  { slug: 'seafood', label: 'Seafood', file: 'seafood.webp' },
  { slug: 'pasta', label: 'Pasta', file: 'pasta.webp' },
  { slug: 'italian', label: 'Italian', file: 'italian.webp' },
  { slug: 'continental', label: 'Continental', file: 'continental.webp' },
  { slug: 'mexican', label: 'Mexican', file: 'mexican.webp' },
  { slug: 'thai', label: 'Thai', file: 'thai.webp' },
  { slug: 'japanese', label: 'Japanese', file: 'japanese.webp' },
  { slug: 'asian', label: 'Asian', file: 'asian.webp' },
  { slug: 'mediterranean', label: 'Mediterranean', file: 'mediterranean.webp' },
  { slug: 'fries', label: 'French Fries', file: 'french_fries.webp' },
  { slug: 'soups', label: 'Soups', file: 'soups.webp' },
  { slug: 'salads', label: 'Salads', file: 'salads.webp' },
  { slug: 'healthy', label: 'Healthy', file: 'healthy_food.webp' },
  { slug: 'jain', label: 'Jain', file: 'jain_food.webp' },
  { slug: 'desserts', label: 'Desserts', file: 'desserts.webp' },
  { slug: 'ice_cream', label: 'Ice Cream', file: 'ice_cream.webp' },
  { slug: 'sweets', label: 'Sweets', file: 'sweets.webp' },
  { slug: 'bakery', label: 'Bakery', file: 'bakery.webp' },
  { slug: 'beverages', label: 'Beverages', file: 'beverages.webp' },
  { slug: 'shakes', label: 'Shakes', file: 'shakes_smoothies.webp' },
];

const FILES: Record<string, ImageSourcePropType> = {
  'asian.webp': require('../../../public/tokajo_circle_categories/asian.webp'),
  'bakery.webp': require('../../../public/tokajo_circle_categories/bakery.webp'),
  'bbq.webp': require('../../../public/tokajo_circle_categories/bbq.webp'),
  'beverages.webp': require('../../../public/tokajo_circle_categories/beverages.webp'),
  'biryani.webp': require('../../../public/tokajo_circle_categories/biryani.webp'),
  'burger.webp': require('../../../public/tokajo_circle_categories/burger.webp'),
  'chaat.webp': require('../../../public/tokajo_circle_categories/chaat.webp'),
  'chicken.webp': require('../../../public/tokajo_circle_categories/chicken.webp'),
  'chinese.webp': require('../../../public/tokajo_circle_categories/chinese.webp'),
  'chole_bhature.webp': require('../../../public/tokajo_circle_categories/chole_bhature.webp'),
  'continental.webp': require('../../../public/tokajo_circle_categories/continental.webp'),
  'desserts.webp': require('../../../public/tokajo_circle_categories/desserts.webp'),
  'dosa.webp': require('../../../public/tokajo_circle_categories/dosa.webp'),
  'french_fries.webp': require('../../../public/tokajo_circle_categories/french_fries.webp'),
  'healthy_food.webp': require('../../../public/tokajo_circle_categories/healthy_food.webp'),
  'ice_cream.webp': require('../../../public/tokajo_circle_categories/ice_cream.webp'),
  'idli.webp': require('../../../public/tokajo_circle_categories/idli.webp'),
  'italian.webp': require('../../../public/tokajo_circle_categories/italian.webp'),
  'jain_food.webp': require('../../../public/tokajo_circle_categories/jain_food.webp'),
  'japanese.webp': require('../../../public/tokajo_circle_categories/japanese.webp'),
  'kachori.webp': require('../../../public/tokajo_circle_categories/kachori.webp'),
  'kebabs.webp': require('../../../public/tokajo_circle_categories/kebabs.webp'),
  'mediterranean.webp': require('../../../public/tokajo_circle_categories/mediterranean.webp'),
  'mexican.webp': require('../../../public/tokajo_circle_categories/mexican.webp'),
  'momos.webp': require('../../../public/tokajo_circle_categories/momos.webp'),
  'mutton.webp': require('../../../public/tokajo_circle_categories/mutton.webp'),
  'noodles.webp': require('../../../public/tokajo_circle_categories/noodles.webp'),
  'north_indian.webp': require('../../../public/tokajo_circle_categories/north_indian.webp'),
  'paratha.webp': require('../../../public/tokajo_circle_categories/paratha.webp'),
  'pasta.webp': require('../../../public/tokajo_circle_categories/pasta.webp'),
  'pav_bhaji.webp': require('../../../public/tokajo_circle_categories/pav_bhaji.webp'),
  'pizza.webp': require('../../../public/tokajo_circle_categories/pizza.webp'),
  'poori_bhaji.webp': require('../../../public/tokajo_circle_categories/poori_bhaji.webp'),
  'rajma_chawal.webp': require('../../../public/tokajo_circle_categories/rajma_chawal.webp'),
  'rolls_wraps.webp': require('../../../public/tokajo_circle_categories/rolls_wraps.webp'),
  'salads.webp': require('../../../public/tokajo_circle_categories/salads.webp'),
  'samosa.webp': require('../../../public/tokajo_circle_categories/samosa.webp'),
  'sandwich.webp': require('../../../public/tokajo_circle_categories/sandwich.webp'),
  'seafood.webp': require('../../../public/tokajo_circle_categories/seafood.webp'),
  'shakes_smoothies.webp': require('../../../public/tokajo_circle_categories/shakes_smoothies.webp'),
  'shawarma.webp': require('../../../public/tokajo_circle_categories/shawarma.webp'),
  'snacks.webp': require('../../../public/tokajo_circle_categories/snacks.webp'),
  'soups.webp': require('../../../public/tokajo_circle_categories/soups.webp'),
  'south_indian.webp': require('../../../public/tokajo_circle_categories/south_indian.webp'),
  'street_food.webp': require('../../../public/tokajo_circle_categories/street_food.webp'),
  'sweets.webp': require('../../../public/tokajo_circle_categories/sweets.webp'),
  'tandoori.webp': require('../../../public/tokajo_circle_categories/tandoori.webp'),
  'thai.webp': require('../../../public/tokajo_circle_categories/thai.webp'),
  'thali.webp': require('../../../public/tokajo_circle_categories/thali.webp'),
  'vada_pav.webp': require('../../../public/tokajo_circle_categories/vada_pav.webp'),
};

export const CIRCLE_CATEGORIES: CircleCategory[] = ORDER.map((row) => ({
  id: row.slug,
  slug: row.slug,
  label: row.label,
  image: FILES[row.file],
}));

export const CATEGORY_PREVIEW_COUNT = 8;
