import { StyleSheet } from 'react-native';

import { fonts } from '@/constants/typography';

const ORANGE = '#F97316';
const GREEN = '#12833B';

export const styles = StyleSheet.create({
  separator: {
    height: 1,
    backgroundColor: '#E8E2DC',
    marginHorizontal: 28,
    marginTop: 2,
    marginBottom: 16,
  },
  card: {
    marginHorizontal: 16,
    marginBottom: 18,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    shadowColor: '#8A3B12',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  cardPressed: {
    opacity: 0.97,
    transform: [{ scale: 0.994 }],
  },
  imageWrap: {
    height: 176,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  imageEmpty: {
    backgroundColor: '#EFEFEF',
  },
  imageShade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 72,
    backgroundColor: 'rgba(0,0,0,0.28)',
  },
  imageShadeLight: {
    height: 36,
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  promoted: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'rgba(17,17,17,0.7)',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  promotedText: {
    color: '#FFFFFF',
    fontFamily: fonts.uiBold,
    fontSize: 10,
    letterSpacing: 0.3,
  },
  heart: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  offerChip: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    maxWidth: '78%',
    backgroundColor: ORANGE,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  offerChipText: {
    color: '#FFFFFF',
    fontFamily: fonts.uiBold,
    fontSize: 12,
  },
  body: {
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 13,
    gap: 5,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  name: {
    flex: 1,
    fontFamily: fonts.displayBold,
    fontSize: 17,
    color: '#171717',
    letterSpacing: -0.3,
  },
  ratingWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  ratingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: GREEN,
    borderRadius: 7,
    paddingHorizontal: 7,
    paddingVertical: 3.5,
  },
  ratingText: {
    color: '#FFFFFF',
    fontFamily: fonts.uiBold,
    fontSize: 12,
  },
  ratingCount: {
    fontFamily: fonts.uiSemi,
    fontSize: 11.5,
    color: '#9A9A9A',
  },
  cuisines: {
    fontFamily: fonts.ui,
    fontSize: 13,
    color: '#8A8A8A',
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 7,
    marginTop: 4,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontFamily: fonts.uiSemi,
    fontSize: 12.5,
    color: '#4B4B4B',
  },
  dot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: '#C4C4C4',
    marginRight: 2,
  },
  vegChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#EAF7EF',
    borderRadius: 6,
    paddingHorizontal: 7,
    paddingVertical: 3,
    marginLeft: 2,
  },
  vegSquare: {
    width: 11,
    height: 11,
    borderRadius: 2,
    borderWidth: 1.4,
    borderColor: GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vegDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: GREEN,
  },
  vegChipText: {
    fontFamily: fonts.uiBold,
    fontSize: 10.5,
    color: GREEN,
  },
});
